clear;
load('theta_pdf_new.mat');
load('c_string.mat');

fig = figure();
hold on

% shear
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(1,:),'--','linewidth',1,'Color',[1,1,1]*0.7);
% shear with still rod
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(2,:),'-.','linewidth',1,'Color',[1,1,1]*0.7);
% pure flux
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(3,:),':','linewidth',1,'Color',[1,1,1]*0.7);
% forward
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(4,:),'-','linewidth',1,'Color',c_string{51}{4});
% inverse
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(5,:),'-','linewidth',1,'Color',c_string{5}{1});
% neutral
plot(0.5*(edge(1:end-1) + edge(2:end)),N_save(6,:),'-','linewidth',1,'Color',c_string{6}{3});

xlb = xlabel('\theta^{(L)}/\pi');
ylb = ylabel('pdf');
xlim([0 0.5])

% lgd = legend('Shear',...
%     'Shear with still rod array',...
%     'Moving rod array with no shear',...
%     '$\theta \approx \pi/2$',...
%     '$\theta \approx 0$',...
%     '$\theta \approx \pi/4$',...
%     'location','southeast');
% 
% lgd.NumColumns = 1;
% lgd.Units = 'centimeters';
% lgd.Position = [2.3,3.8,1.8,1.5];
% lgd.ItemTokenSize = [10,1];
% legend boxoff

% set(gcf,'MenuBar','figure',...
%     'Units','centimeters',...
%     'Position',[5,5,6,6],...
%     'Resize',0,...
%     'PaperUnits','centimeters',...
%     'PaperSize',[6 6]);

set(gca,'FontName','Arial',...
    'FontSize',7,...
    'FontUnits','Points',...
    'Units','centimeters',...
    'Position',[1,1,4,4],...
    'YDir','normal',...
    'Box','on',...
    'Units','centimeters',...
    'looseInset',[0,0,0,0]...
    );
ax = gca;
ax.PlotBoxAspectRatio = [4,3,1];
pos = tightPosition(ax);
pos_out = ax.OuterPosition;