%%% Plot time-averaged Q 
clear;
addpath(genpath('X:\Xinyu_Si_X\MATLAB_master\MatLab_Toolbox'));
crtfd = pwd;
load('c_string.mat');
load('Fig_3c.mat');

mainfolder = {'E:\Xinyu_Si_Post_data\231201\set1',...
    'E:\Xinyu_Si_Post_data\231201\set3',...
    'E:\Xinyu_Si_Post_data\231201\set8',...
    'E:\Xinyu_Si_Post_data\231201\set6',...
    'E:\Xinyu_Si_Post_data\231201\set12',...
    'E:\Xinyu_Si_Post_data\231201\set9',...
    };

load('Dissipation_240624.mat');  % from nu*omege^2, in folder order [ 1 3 8 6 12 9];

fig = figure();
hold on

L_scale = 3.7;

linetype_all = {'--','-.',':','-','-','-'};
for i = 1: length(mainfolder)
    % load(fullfile(mainfolder{i},'FST_avg.mat'));
    % Q_select{i} = Q_s_mean_save;

    % plot(L/ppcm,mean(Q_select,1),'-','linewidth',1.5);
    plot(L/ppcm/L_scale,mean(Q_select{i},1)./Dissipation(i)/2,linetype_all{i},'linewidth',1.0);
end

colororder({'#b3b3b3','#b3b3b3','#b3b3b3',c_string{51}{4},c_string{6}{3},c_string{5}{1}});

xlb = xlabel('L/W');
ylb = ylabel('\langle\Pi_S^{(L)}\rangle/2\nu\Omega');

% lgd = legend('Shear',...
%     'Shear with still rod array',...
%     'Moving rod array with no shear',...
%     '$\theta \approx \pi/2$',...
%     '$\theta \approx 0$',...
%     '$\theta \approx \pi/4$',...
%     'location','southeast');
% 
% lgd.NumColumns = 1;
% lgd.Units = 'centimeters';
% lgd.Position = [2.3,3.6,1.8,1.5];
% lgd.ItemTokenSize = [10,1];
% legend boxoff

% set(gcf,'MenuBar','figure',...
%     'Units','centimeters',...
%     'Position',[5,5,6,6],...
%     'Resize',0,...
%     'PaperUnits','centimeters',...
%     'PaperSize',[6 6]);

set(gca,'FontName','Arial',...
    'FontSize',7,...
    'FontUnits','Points',...
    'Units','centimeters',...
    'Position',[1.5,1.5,4,4],...
    'YDir','normal',...
    'Box','on',...
    'Units','centimeters',...
    'looseInset',[0,0,0,0]...
    );
ax = gca;
ax.PlotBoxAspectRatio = [4,3,1];
pos = tightPosition(ax);
pos_out = ax.OuterPosition;






